<?php

namespace Tests\Feature\Services;


use App\Services\PassportClientCreator;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class PassportClientCreatorTest extends TestCase
{
    use RefreshDatabase;

    public function test_CreateClient(){

        $newPassportCreator = new PassportClientCreator();

        $id = '';
        $secret = '';
        $callbackUrl = '';
        $name = '';

        $newPassportCreator->create($id, $secret, $callbackUrl, $name);

        $testClient = DB::table(PassportClientCreator::TABLE_NAME)
            ->where(['id'=> $id,
                'secret' => $secret,
                'redirect' => $callbackUrl,
                'name'=> $name])
            ->first();

        $this->assertNotNull($testClient);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
